//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaneVAssistant.Responses.Main {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaneVAssistant.Responses.Main.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s start over..
        /// </summary>
        public static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can I help you with?.
        /// </summary>
        public static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I&apos;m not able to help with that..
        /// </summary>
        public static string CONFUSED {
            get {
                return ResourceManager.GetString("CONFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it looks like something went wrong..
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        public static string GREETING {
            get {
                return ResourceManager.GetString("GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, {0}!.
        /// </summary>
        public static string GREETING_WITH_NAME {
            get {
                return ResourceManager.GetString("GREETING_WITH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is SQL?.
        /// </summary>
        public static string HELP_BTN_5 {
            get {
                return ResourceManager.GetString("HELP_BTN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is an SQL server?.
        /// </summary>
        public static string HELP_BTN_6 {
            get {
                return ResourceManager.GetString("HELP_BTN_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Oracle?.
        /// </summary>
        public static string HELP_BTN_7 {
            get {
                return ResourceManager.GetString("HELP_BTN_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is an Oracle server?.
        /// </summary>
        public static string HELP_BTN_8 {
            get {
                return ResourceManager.GetString("HELP_BTN_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who made you?.
        /// </summary>
        public static string HELP_BTN_TEXT_0 {
            get {
                return ResourceManager.GetString("HELP_BTN_TEXT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you?.
        /// </summary>
        public static string HELP_BTN_TEXT_1 {
            get {
                return ResourceManager.GetString("HELP_BTN_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Service.
        /// </summary>
        public static string HELP_BTN_TEXT_2 {
            get {
                return ResourceManager.GetString("HELP_BTN_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HELP_BTN_TEXT_3 {
            get {
                return ResourceManager.GetString("HELP_BTN_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMSS.
        /// </summary>
        public static string HELP_BTN_TEXT_4 {
            get {
                return ResourceManager.GetString("HELP_BTN_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who made you?.
        /// </summary>
        public static string HELP_BTN_VALUE_0 {
            get {
                return ResourceManager.GetString("HELP_BTN_VALUE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you?.
        /// </summary>
        public static string HELP_BTN_VALUE_1 {
            get {
                return ResourceManager.GetString("HELP_BTN_VALUE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Service.
        /// </summary>
        public static string HELP_BTN_VALUE_2 {
            get {
                return ResourceManager.GetString("HELP_BTN_VALUE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HELP_BTN_VALUE_3 {
            get {
                return ResourceManager.GetString("HELP_BTN_VALUE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation Team.
        /// </summary>
        public static string HELP_BTN_VALUE_4 {
            get {
                return ResourceManager.GetString("HELP_BTN_VALUE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can answer questions related to databases (try &quot;what is sql&quot;), send an email to the team (say &quot;send an email&quot;), redirect you to our site. Why don&apos;t you try clicking one of the buttons below..
        /// </summary>
        public static string HELP_TEXT {
            get {
                return ResourceManager.GetString("HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HELP_TITLE {
            get {
                return ResourceManager.GetString("HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can answer questions related to databases (try &quot;what is sql&quot;), send an email to the team (say &quot;send an email&quot;), redirect you to our site. Why don&apos;t you try clicking one of the buttons below..
        /// </summary>
        public static string INTRO_MESSAGE {
            get {
                return ResourceManager.GetString("INTRO_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Content/NewUserGreeting.json.
        /// </summary>
        public static string INTRO_PATH {
            get {
                return ResourceManager.GetString("INTRO_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Content/ReturningUserGreeting.json.
        /// </summary>
        public static string INTRO_RETURNING {
            get {
                return ResourceManager.GetString("INTRO_RETURNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting... Thank you, glad i could help!.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Content/MainMenuGreeting.json.
        /// </summary>
        public static string MENU_PATH {
            get {
                return ResourceManager.GetString("MENU_PATH", resourceCulture);
            }
        }
    }
}
