// <auto-generated>
// Code generated by LUISGen C:\Users\hnxc\Desktop\git2\DaneVA\DaneVAssistant\DaneVAssistant\DaneVAssistant\Deployment\Resources\Dispatch\en\DaneVirtualAssistanten_Dispatch.json -cs Luis.DispatchLuis -o C:\Users\hnxc\Desktop\git2\DaneVA\DaneVAssistant\DaneVAssistant\DaneVAssistant\Services
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class DispatchLuis: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            l_general, 
            q_chitchat, 
            q_faq, 
            emailSkill, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Category;

            public string[] ContactName;

            public string[] DirectionalReference;

            public string[] EmailSubject;

            public string[] Message;

            public string[] OrderReference;

            public string[] SenderName;

            // Built-in entities
            public double[] number;

            public double[] ordinal;

            // Instance
            public class _Instance
            {
                public InstanceData[] Category;
                public InstanceData[] ContactName;
                public InstanceData[] DirectionalReference;
                public InstanceData[] EmailSubject;
                public InstanceData[] Message;
                public InstanceData[] OrderReference;
                public InstanceData[] SenderName;
                public InstanceData[] number;
                public InstanceData[] ordinal;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<DispatchLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
